---
baseurl: https://heroish.org/blog/
languageCode: en-us
title: Heroish
metaDataFormat: "yaml"
theme: "thought"
disqusShortname: "hero-y"
paginate: 5
enableEmoji: true
publishDir: "blog"
permalinks:
  post: /:section/:title/
params:
  author: "Ree"
  description: "a nerd's web playground"
menu:
  main:
    - Name: "Index"
      Weight: -120
      Identifier: "index"
      URL: "https://lev.kim/"
    - Name: "About"
      Weight: -110
      Identifier: "about"
      URL: "/about/"
    - Name: "Contact"
      Weight: -100
      Identifier: "contact"
      URL: "/contact/"
    - Name: "Exits"
      Weight: -90
      Identifier: "exits"
      URL: "/exits/"
...
