# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Thought"
description = "Personal blogging theme with own art included."
homepage = "http://heroish.org/"
tags = ["", ""]
features = ["", ""]
min_version = 0.17

[author]
  name = "Lev"
  homepage = "https://lev.kim/"
